In [2]:
from array import *
my_array = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print(my_array)
my_list = my_array.tolist()
print(my_list)

array('i', [1, 3, 5, 3, 7, 1, 9, 3])
[1, 3, 5, 3, 7, 1, 9, 3]


In [5]:
import numpy as np
m = np.arange(16).reshape(4,4)
print(m)
result =  np.trace(m)
print("result of trace:", result)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
result of trace: 30


In [3]:
import numpy as np
x = np.array([[0, 4, 2], [20, 3, 1]])
print("Values bigger than 1", x[x>1])

Values bigger than 1 [ 4  2 20  3]


In [4]:
import numpy as np
A = np.array([5, 4, 8, 7])
B = np.array([1, 2, 8, 9])
C = np.array([A+B])
print(C)

[[ 6  6 16 16]]


In [6]:
import numpy as np
X = np.arange(16).reshape(4,4)
print(X)
print("\nSubtracted the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Subtracted the mean of each row of the said matrix:

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]
